<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\models\Ingredient;

class IngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Ingredient::create(['name' => 'Adobo Sauce', 'description' => 'Adobo Sauce']);
        Ingredient::create(['name' => 'All-purpose Flour', 'description' => 'All-purpose Flour']);
        Ingredient::create(['name' => 'Almond Milk (Or Other Non-dairy Milk)', 'description' => 'Almond Milk (Or Other Non-dairy Milk)']);
        Ingredient::create(['name' => 'Andouille Sausage, Sliced', 'description' => 'Andouille Sausage, Sliced']);
        Ingredient::create(['name' => 'Apple Cider', 'description' => 'Apple Cider']);
        Ingredient::create(['name' => 'Apples, Sliced', 'description' => 'Apples, Sliced']);
        Ingredient::create(['name' => 'Arborio Rice', 'description' => 'Arborio Rice']);
        Ingredient::create(['name' => 'Avocado Oil', 'description' => 'Avocado Oil']);
        Ingredient::create(['name' => 'Avocado Sliced For Serving', 'description' => 'Avocado Sliced For Serving']);
        Ingredient::create(['name' => 'Avocado, Diced', 'description' => 'Avocado, Diced']);
        Ingredient::create(['name' => 'Avocado, Halved And Pitted', 'description' => 'Avocado, Halved And Pitted']);
        Ingredient::create(['name' => 'Avocado, Sliced', 'description' => 'Avocado, Sliced']);
        Ingredient::create(['name' => 'Baby Bella Mushrooms Sliced', 'description' => 'Baby Bella Mushrooms Sliced']);
        Ingredient::create(['name' => 'Baby Bella Mushrooms, Halved', 'description' => 'Baby Bella Mushrooms, Halved']);
        Ingredient::create(['name' => 'Baby Bella Or Cremini Mushrooms, Sliced', 'description' => 'Baby Bella Or Cremini Mushrooms, Sliced']);
        Ingredient::create(['name' => 'Baby Potatoes, Halved', 'description' => 'Baby Potatoes, Halved']);
        Ingredient::create(['name' => 'Baby Spinach', 'description' => 'Baby Spinach']);
        Ingredient::create(['name' => 'Ball Mozzarella Torn', 'description' => 'Ball Mozzarella Torn']);
        Ingredient::create(['name' => 'Balsamic Glaze', 'description' => 'Balsamic Glaze']);
        Ingredient::create(['name' => 'Balsamic Vinegar', 'description' => 'Balsamic Vinegar']);
        Ingredient::create(['name' => 'Balsamic Vinegar Simmered For About 10 Minutes', 'description' => 'Balsamic Vinegar Simmered For About 10 Minutes']);
        Ingredient::create(['name' => 'Barbecue Sauce, Plus More For Serving', 'description' => 'Barbecue Sauce, Plus More For Serving']);
        Ingredient::create(['name' => 'Basil, Thinly Sliced', 'description' => 'Basil, Thinly Sliced']);
        Ingredient::create(['name' => 'Bay Leaf', 'description' => 'Bay Leaf']);
        Ingredient::create(['name' => 'Bay Leaves', 'description' => 'Bay Leaves']);
        Ingredient::create(['name' => 'Bay Leaves (Optional)', 'description' => 'Bay Leaves (Optional)']);
        Ingredient::create(['name' => 'Bell Pepper, Thinly Sliced', 'description' => 'Bell Pepper, Thinly Sliced']);
        Ingredient::create(['name' => 'Bell Peppers Chopped', 'description' => 'Bell Peppers Chopped']);
        Ingredient::create(['name' => 'Bell Peppers, Chopped', 'description' => 'Bell Peppers, Chopped']);
        Ingredient::create(['name' => 'Bell Peppers, Tops And Cores Removed', 'description' => 'Bell Peppers, Tops And Cores Removed']);
        Ingredient::create(['name' => 'Biscuit Dough', 'description' => 'Biscuit Dough']);
        Ingredient::create(['name' => 'Black Beans', 'description' => 'Black Beans']);
        Ingredient::create(['name' => 'Black Beans, Rinsed And Drained', 'description' => 'Black Beans, Rinsed And Drained']);
        Ingredient::create(['name' => 'Black Pepper', 'description' => 'Black Pepper']);
        Ingredient::create(['name' => 'Black Peppercorns', 'description' => 'Black Peppercorns']);
        Ingredient::create(['name' => 'Block Feta', 'description' => 'Block Feta']);
        Ingredient::create(['name' => 'Block Firm Tofu, Frozen In Package For 24 Hours And Defrosted', 'description' => 'Block Firm Tofu, Frozen In Package For 24 Hours And Defrosted']);
        Ingredient::create(['name' => 'Blue Cheese', 'description' => 'Blue Cheese']);
        Ingredient::create(['name' => 'Bone-in Or Boneless Chicken Thighs', 'description' => 'Bone-in Or Boneless Chicken Thighs']);
        Ingredient::create(['name' => 'Bone-in Skin-on Chicken Thighs', 'description' => 'Bone-in Skin-on Chicken Thighs']);
        Ingredient::create(['name' => 'Bone-in, Skin-on Chicken Thighs', 'description' => 'Bone-in, Skin-on Chicken Thighs']);
        Ingredient::create(['name' => 'Bone-in, Skin-on Chicken Thighs And Drumsticks', 'description' => 'Bone-in, Skin-on Chicken Thighs And Drumsticks']);
        Ingredient::create(['name' => 'Bone-in, Skin-on Chicken Thighs, Trimmed', 'description' => 'Bone-in, Skin-on Chicken Thighs, Trimmed']);
        Ingredient::create(['name' => 'Boneless Pork Chops', 'description' => 'Boneless Pork Chops']);
        Ingredient::create(['name' => 'Boneless Skinless Chicken Breasts', 'description' => 'Boneless Skinless Chicken Breasts']);
        Ingredient::create(['name' => 'Boneless Skinless Chicken Breasts (About 4)', 'description' => 'Boneless Skinless Chicken Breasts (About 4)']);
        Ingredient::create(['name' => 'Boneless Skinless Chicken Breasts, Cut Into 1 Pieces', 'description' => 'Boneless Skinless Chicken Breasts, Cut Into 1 Pieces']);
        Ingredient::create(['name' => 'Boneless Skinless Chicken Breasts, Cut Into Strips', 'description' => 'Boneless Skinless Chicken Breasts, Cut Into Strips']);
        Ingredient::create(['name' => 'Boneless Skinless Chicken Breasts, Halved', 'description' => 'Boneless Skinless Chicken Breasts, Halved']);
        Ingredient::create(['name' => 'Box Lasagna Noodles', 'description' => 'Box Lasagna Noodles']);
        Ingredient::create(['name' => 'Broccoli Cut Into Florets', 'description' => 'Broccoli Cut Into Florets']);
        Ingredient::create(['name' => 'Brown Sugar', 'description' => 'Brown Sugar']);
        Ingredient::create(['name' => 'Bucatini', 'description' => 'Bucatini']);
        Ingredient::create(['name' => 'Bunches Kale, Stems Removed And Leaves Torn (About Packed Cups Total)', 'description' => 'Bunches Kale, Stems Removed And Leaves Torn (About Packed Cups Total)']);
        Ingredient::create(['name' => 'Butter', 'description' => 'Butter']);
        Ingredient::create(['name' => 'Butter, Divided', 'description' => 'Butter, Divided']);
        Ingredient::create(['name' => 'Butter, Softened, Divided', 'description' => 'Butter, Softened, Divided']);
        Ingredient::create(['name' => 'Butter,melted', 'description' => 'Butter,melted']);
        Ingredient::create(['name' => 'Buttermilk', 'description' => 'Buttermilk']);
        Ingredient::create(['name' => 'Can Black Beans, Drained And Rinsed', 'description' => 'Can Black Beans, Drained And Rinsed']);
        Ingredient::create(['name' => 'Can Black Beans, Rinsed And Drained', 'description' => 'Can Black Beans, Rinsed And Drained']);
        Ingredient::create(['name' => 'Can Coconut Milk', 'description' => 'Can Coconut Milk']);
        Ingredient::create(['name' => 'Can Crushed Tomatoes', 'description' => 'Can Crushed Tomatoes']);
        Ingredient::create(['name' => 'Can Diced Tomatoes', 'description' => 'Can Diced Tomatoes']);
        Ingredient::create(['name' => 'Can Fire Roasted Tomatoes', 'description' => 'Can Fire Roasted Tomatoes']);
        Ingredient::create(['name' => 'Can Fire-roasted Diced Tomatoes', 'description' => 'Can Fire-roasted Diced Tomatoes']);
        Ingredient::create(['name' => 'Can Kidney Beans, Drained And Rinsed', 'description' => 'Can Kidney Beans, Drained And Rinsed']);
        Ingredient::create(['name' => 'Can Pinto Beans, Drained And Rinsed', 'description' => 'Can Pinto Beans, Drained And Rinsed']);
        Ingredient::create(['name' => 'Can Pinto, Kidney, White Beans, Or Black Beans, Drained And Rinsed', 'description' => 'Can Pinto, Kidney, White Beans, Or Black Beans, Drained And Rinsed']);
        Ingredient::create(['name' => 'Can Refried Beans', 'description' => 'Can Refried Beans']);
        Ingredient::create(['name' => 'Can Whole Tomatoes, Crushed', 'description' => 'Can Whole Tomatoes, Crushed']);
        Ingredient::create(['name' => 'Canned Water Chestnuts, Drained And Sliced', 'description' => 'Canned Water Chestnuts, Drained And Sliced']);
        Ingredient::create(['name' => 'Canola Oil, Divided', 'description' => 'Canola Oil, Divided']);
        Ingredient::create(['name' => 'Canola Or Vegetable Oil, Divided', 'description' => 'Canola Or Vegetable Oil, Divided']);
        Ingredient::create(['name' => 'Cans Hominy, Drained And Rinsed', 'description' => 'Cans Hominy, Drained And Rinsed']);
        Ingredient::create(['name' => 'Capers, Drained', 'description' => 'Capers, Drained']);
        Ingredient::create(['name' => 'Carrots, Peeled And Chopped', 'description' => 'Carrots, Peeled And Chopped']);
        Ingredient::create(['name' => 'Carrots, Peeled And Diced', 'description' => 'Carrots, Peeled And Diced']);
        Ingredient::create(['name' => 'Carrots, Peeled And Finely Chopped', 'description' => 'Carrots, Peeled And Finely Chopped']);
        Ingredient::create(['name' => 'Cayenne', 'description' => 'Cayenne']);
        Ingredient::create(['name' => 'Cayenne Pepper', 'description' => 'Cayenne Pepper']);
        Ingredient::create(['name' => 'Cherry Or Grape Tomatoes', 'description' => 'Cherry Or Grape Tomatoes']);
        Ingredient::create(['name' => 'Cherry Tomatoes, Halved', 'description' => 'Cherry Tomatoes, Halved']);
        Ingredient::create(['name' => 'Chicken', 'description' => 'Chicken']);
        Ingredient::create(['name' => 'Chicken Breasts', 'description' => 'Chicken Breasts']);
        Ingredient::create(['name' => 'Chicken Breasts,thinly Sliced', 'description' => 'Chicken Breasts,thinly Sliced']);
        Ingredient::create(['name' => 'Chicken Broth Swanson Chicken Broth', 'description' => 'Chicken Broth Swanson Chicken Broth']);
        Ingredient::create(['name' => 'Chicken Or Vegetable Broth', 'description' => 'Chicken Or Vegetable Broth']);
        Ingredient::create(['name' => 'Chili Powder', 'description' => 'Chili Powder']);
        Ingredient::create(['name' => 'Chilis From Canned Chilis In Adobo, Depending On Spice Preference, Minced', 'description' => 'Chilis From Canned Chilis In Adobo, Depending On Spice Preference, Minced']);
        Ingredient::create(['name' => 'Chinese Cooking Wine Or Dry Sherry', 'description' => 'Chinese Cooking Wine Or Dry Sherry']);
        Ingredient::create(['name' => 'Chipotle Pepper In Adobo Sauce', 'description' => 'Chipotle Pepper In Adobo Sauce']);
        Ingredient::create(['name' => 'Chipotle Vegan Queso', 'description' => 'Chipotle Vegan Queso']);
        Ingredient::create(['name' => 'Chipotles In Adobo', 'description' => 'Chipotles In Adobo']);
        Ingredient::create(['name' => 'Chopped Basil', 'description' => 'Chopped Basil']);
        Ingredient::create(['name' => 'Chopped Chipotle Chiles In Adobo Sauce', 'description' => 'Chopped Chipotle Chiles In Adobo Sauce']);
        Ingredient::create(['name' => 'Chopped Fresh Basil Leaves, Plus More For Serving', 'description' => 'Chopped Fresh Basil Leaves, Plus More For Serving']);
        Ingredient::create(['name' => 'Chopped Fresh Cilantro', 'description' => 'Chopped Fresh Cilantro']);
        Ingredient::create(['name' => 'Chopped Fresh Parsley, Divided', 'description' => 'Chopped Fresh Parsley, Divided']);
        Ingredient::create(['name' => 'Chopped Fresh Parsley, For Garnish', 'description' => 'Chopped Fresh Parsley, For Garnish']);
        Ingredient::create(['name' => 'Chopped Fresh Rosemary', 'description' => 'Chopped Fresh Rosemary']);
        Ingredient::create(['name' => 'Chopped Fresh Thyme', 'description' => 'Chopped Fresh Thyme']);
        Ingredient::create(['name' => 'Chopped Fresh Thyme, Divided, Plus More Leaves For Serving', 'description' => 'Chopped Fresh Thyme, Divided, Plus More Leaves For Serving']);
        Ingredient::create(['name' => 'Chopped Lettuce', 'description' => 'Chopped Lettuce']);
        Ingredient::create(['name' => 'Chopped Parsley, For Garnish', 'description' => 'Chopped Parsley, For Garnish']);
        Ingredient::create(['name' => 'Chopped Pecans', 'description' => 'Chopped Pecans']);
        Ingredient::create(['name' => 'Chopped Scallions, For Serving', 'description' => 'Chopped Scallions, For Serving']);
        Ingredient::create(['name' => 'Chopped Tomatoes', 'description' => 'Chopped Tomatoes']);
        Ingredient::create(['name' => 'Cilantro For Serving', 'description' => 'Cilantro For Serving']);
        Ingredient::create(['name' => 'Cilantro, For Serving', 'description' => 'Cilantro, For Serving']);
        Ingredient::create(['name' => 'Cilntro Leaves, For Garnish', 'description' => 'Cilntro Leaves, For Garnish']);
        Ingredient::create(['name' => 'Cloves Garlic', 'description' => 'Cloves Garlic']);
        Ingredient::create(['name' => 'Cloves Garlic Minced', 'description' => 'Cloves Garlic Minced']);
        Ingredient::create(['name' => 'Cloves Garlic Smashed And Peeled', 'description' => 'Cloves Garlic Smashed And Peeled']);
        Ingredient::create(['name' => 'Cloves Garlic, Finely Chopped', 'description' => 'Cloves Garlic, Finely Chopped']);
        Ingredient::create(['name' => 'Cloves Garlic, Minced', 'description' => 'Cloves Garlic, Minced']);
        Ingredient::create(['name' => 'Cloves Garlic, Roughly Chopped', 'description' => 'Cloves Garlic, Roughly Chopped']);
        Ingredient::create(['name' => 'Cloves Garlic, Smashed', 'description' => 'Cloves Garlic, Smashed']);
        Ingredient::create(['name' => 'Cloves Garlic, Unpeeled', 'description' => 'Cloves Garlic, Unpeeled']);
        Ingredient::create(['name' => 'Cloves Minced', 'description' => 'Cloves Minced']);
        Ingredient::create(['name' => 'Cod (Or Other Flaky White Fish)', 'description' => 'Cod (Or Other Flaky White Fish)']);
        Ingredient::create(['name' => 'Cold Water', 'description' => 'Cold Water']);
        Ingredient::create(['name' => 'Cooked Angel Hair, For Serving', 'description' => 'Cooked Angel Hair, For Serving']);
        Ingredient::create(['name' => 'Cooked Green Lentils (From About 1 Cup Dried)', 'description' => 'Cooked Green Lentils (From About 1 Cup Dried)']);
        Ingredient::create(['name' => 'Cooked Rice', 'description' => 'Cooked Rice']);
        Ingredient::create(['name' => 'Cooked Rice, For Serving', 'description' => 'Cooked Rice, For Serving']);
        Ingredient::create(['name' => 'Cooked Shredded Chicken', 'description' => 'Cooked Shredded Chicken']);
        Ingredient::create(['name' => 'Cooked White Rice (Preferably Leftover)', 'description' => 'Cooked White Rice (Preferably Leftover)']);
        Ingredient::create(['name' => 'Cooked White Rice For Serving', 'description' => 'Cooked White Rice For Serving']);
        Ingredient::create(['name' => 'Cooked White Rice, For Serving', 'description' => 'Cooked White Rice, For Serving']);
        Ingredient::create(['name' => 'Cooked White Rice, For Serving (Optional)', 'description' => 'Cooked White Rice, For Serving (Optional)']);
        Ingredient::create(['name' => 'Cooked White Rice, Preferably Day Old', 'description' => 'Cooked White Rice, Preferably Day Old']);
        Ingredient::create(['name' => 'Cooking Spray', 'description' => 'Cooking Spray']);
        Ingredient::create(['name' => 'Coriander Powder', 'description' => 'Coriander Powder']);
        Ingredient::create(['name' => 'Corn', 'description' => 'Corn']);
        Ingredient::create(['name' => 'Corn Chips, Such As Fritos, For Topping', 'description' => 'Corn Chips, Such As Fritos, For Topping']);
        Ingredient::create(['name' => 'Corn Kernels', 'description' => 'Corn Kernels']);
        Ingredient::create(['name' => 'Corn Tortillas', 'description' => 'Corn Tortillas']);
        Ingredient::create(['name' => 'Corn Tortillas Warmed For Serving', 'description' => 'Corn Tortillas Warmed For Serving']);
        Ingredient::create(['name' => 'Cornmeal For Pan', 'description' => 'Cornmeal For Pan']);
        Ingredient::create(['name' => 'Cornstarch', 'description' => 'Cornstarch']);
        Ingredient::create(['name' => 'Cornstarch (Optional)', 'description' => 'Cornstarch (Optional)']);
        Ingredient::create(['name' => 'Cornstarch, Divided', 'description' => 'Cornstarch, Divided']);
        Ingredient::create(['name' => 'Crumbled Red Onion Thinly Sliced', 'description' => 'Crumbled Red Onion Thinly Sliced']);
        Ingredient::create(['name' => 'Crushed Red Pepper Flake', 'description' => 'Crushed Red Pepper Flake']);
        Ingredient::create(['name' => 'Crushed Red Pepper Flakes', 'description' => 'Crushed Red Pepper Flakes']);
        Ingredient::create(['name' => 'Crushed Red Pepper Flakes, Plus More To Taste', 'description' => 'Crushed Red Pepper Flakes, Plus More To Taste']);
        Ingredient::create(['name' => 'Crushed Tomatoes', 'description' => 'Crushed Tomatoes']);
        Ingredient::create(['name' => 'Cubed Cooked Turkey', 'description' => 'Cubed Cooked Turkey']);
        Ingredient::create(['name' => 'Cumin', 'description' => 'Cumin']);
        Ingredient::create(['name' => 'Cup Water', 'description' => 'Cup Water']);
        Ingredient::create(['name' => 'Curry Powder', 'description' => 'Curry Powder']);
        Ingredient::create(['name' => 'Dijon Mustard', 'description' => 'Dijon Mustard']);
        Ingredient::create(['name' => 'Divided Kosher Salt', 'description' => 'Divided Kosher Salt']);
        Ingredient::create(['name' => 'Divided, Plus More For Pan', 'description' => 'Divided, Plus More For Pan']);
        Ingredient::create(['name' => 'Drained Chickpeas', 'description' => 'Drained Chickpeas']);
        Ingredient::create(['name' => 'Dried Oregano', 'description' => 'Dried Oregano']);
        Ingredient::create(['name' => 'Dried Oregano Divided', 'description' => 'Dried Oregano Divided']);
        Ingredient::create(['name' => 'Dried Oregano, Divided', 'description' => 'Dried Oregano, Divided']);
        Ingredient::create(['name' => 'Dried Red Chilis', 'description' => 'Dried Red Chilis']);
        Ingredient::create(['name' => 'Dry Pasta, Such As Cavatappi', 'description' => 'Dry Pasta, Such As Cavatappi']);
        Ingredient::create(['name' => 'Dry White Wine', 'description' => 'Dry White Wine']);
        Ingredient::create(['name' => 'Egg Noodles', 'description' => 'Egg Noodles']);
        Ingredient::create(['name' => 'Egg Noodles, Cooked', 'description' => 'Egg Noodles, Cooked']);
        Ingredient::create(['name' => 'Eggs', 'description' => 'Eggs']);
        Ingredient::create(['name' => 'Eggs, Lightly Whisked', 'description' => 'Eggs, Lightly Whisked']);
        Ingredient::create(['name' => 'Everything Bagel Seasoning', 'description' => 'Everything Bagel Seasoning']);
        Ingredient::create(['name' => 'Extra-virgin', 'description' => 'Extra-virgin']);
        Ingredient::create(['name' => 'Extra-virgin Olive Oi', 'description' => 'Extra-virgin Olive Oi']);
        Ingredient::create(['name' => 'Extra-virgin Olive Oil', 'description' => 'Extra-virgin Olive Oil']);
        Ingredient::create(['name' => 'Extra-virgin Olive Oil Divided', 'description' => 'Extra-virgin Olive Oil Divided']);
        Ingredient::create(['name' => 'Extra-virgin Olive Oil, Divided', 'description' => 'Extra-virgin Olive Oil, Divided']);
        Ingredient::create(['name' => 'Extra-virgin Olive Oil, Plus More For Drizzling', 'description' => 'Extra-virgin Olive Oil, Plus More For Drizzling']);
        Ingredient::create(['name' => 'Fettuccine', 'description' => 'Fettuccine']);
        Ingredient::create(['name' => 'Finely Chopped Fresh Rosemary', 'description' => 'Finely Chopped Fresh Rosemary']);
        Ingredient::create(['name' => 'Finely Grated Parmesan', 'description' => 'Finely Grated Parmesan']);
        Ingredient::create(['name' => 'Firm Tofu Drained', 'description' => 'Firm Tofu Drained']);
        Ingredient::create(['name' => 'Fish Sauce', 'description' => 'Fish Sauce']);
        Ingredient::create(['name' => 'Flank Steak, Cut Into Strips', 'description' => 'Flank Steak, Cut Into Strips']);
        Ingredient::create(['name' => 'Fresh Basil', 'description' => 'Fresh Basil']);
        Ingredient::create(['name' => 'Fresh Basil, For Garnish', 'description' => 'Fresh Basil, For Garnish']);
        Ingredient::create(['name' => 'Fresh Cilantro, For Garnish,', 'description' => 'Fresh Cilantro, For Garnish,']);
        Ingredient::create(['name' => 'Fresh Ginger, Minced', 'description' => 'Fresh Ginger, Minced']);
        Ingredient::create(['name' => 'Fresh Ginger, Peeled And Thinly Sliced', 'description' => 'Fresh Ginger, Peeled And Thinly Sliced']);
        Ingredient::create(['name' => 'Fresh Mozzarella, Sliced', 'description' => 'Fresh Mozzarella, Sliced']);
        Ingredient::create(['name' => 'Fresh Parsley, Finely Chopped Plus More For Garnish', 'description' => 'Fresh Parsley, Finely Chopped Plus More For Garnish']);
        Ingredient::create(['name' => 'Fresh Rosemary (Optional)', 'description' => 'Fresh Rosemary (Optional)']);
        Ingredient::create(['name' => 'Fresh Thyme', 'description' => 'Fresh Thyme']);
        Ingredient::create(['name' => 'Fresh Thyme Leaves', 'description' => 'Fresh Thyme Leaves']);
        Ingredient::create(['name' => 'Fresh Thyme Leaves, Plus 4 Sprigs', 'description' => 'Fresh Thyme Leaves, Plus 4 Sprigs']);
        Ingredient::create(['name' => 'Freshly Basil For Serving', 'description' => 'Freshly Basil For Serving']);
        Ingredient::create(['name' => 'Freshly Chopped Basil, For Garnish', 'description' => 'Freshly Chopped Basil, For Garnish']);
        Ingredient::create(['name' => 'Freshly Chopped Cilantro', 'description' => 'Freshly Chopped Cilantro']);
        Ingredient::create(['name' => 'Freshly Chopped Cilantro, Divided', 'description' => 'Freshly Chopped Cilantro, Divided']);
        Ingredient::create(['name' => 'Freshly Chopped Cilantro, For Garnish', 'description' => 'Freshly Chopped Cilantro, For Garnish']);
        Ingredient::create(['name' => 'Freshly Chopped Cilantro, For Serving', 'description' => 'Freshly Chopped Cilantro, For Serving']);
        Ingredient::create(['name' => 'Freshly Chopped Dill', 'description' => 'Freshly Chopped Dill']);
        Ingredient::create(['name' => 'Freshly Chopped Dill, Plus More For Garnish', 'description' => 'Freshly Chopped Dill, Plus More For Garnish']);
        Ingredient::create(['name' => 'Freshly Chopped Herbs (Such As Basil And Parsley Plus More For Garnish', 'description' => 'Freshly Chopped Herbs (Such As Basil And Parsley Plus More For Garnish']);
        Ingredient::create(['name' => 'Freshly Chopped Parsley', 'description' => 'Freshly Chopped Parsley']);
        Ingredient::create(['name' => 'Freshly Chopped Parsley, For Garnish', 'description' => 'Freshly Chopped Parsley, For Garnish']);
        Ingredient::create(['name' => 'Freshly Chopped Parsley, For Serving', 'description' => 'Freshly Chopped Parsley, For Serving']);
        Ingredient::create(['name' => 'Freshly Chopped Parsley, Plus More For Garnish', 'description' => 'Freshly Chopped Parsley, Plus More For Garnish']);
        Ingredient::create(['name' => 'Freshly Grated Ginger', 'description' => 'Freshly Grated Ginger']);
        Ingredient::create(['name' => 'Freshly Grated Parmesan', 'description' => 'Freshly Grated Parmesan']);
        Ingredient::create(['name' => 'Freshly Grated Parmesan For Serving', 'description' => 'Freshly Grated Parmesan For Serving']);
        Ingredient::create(['name' => 'Freshly Grated Parmesan Plus More For Serving', 'description' => 'Freshly Grated Parmesan Plus More For Serving']);
        Ingredient::create(['name' => 'Freshly Grated Parmesan, Divided', 'description' => 'Freshly Grated Parmesan, Divided']);
        Ingredient::create(['name' => 'Freshly Grated Parmesan, Plus More For Serving', 'description' => 'Freshly Grated Parmesan, Plus More For Serving']);
        Ingredient::create(['name' => 'Freshly Grated Pecorino, For Garnish', 'description' => 'Freshly Grated Pecorino, For Garnish']);
        Ingredient::create(['name' => 'Freshly Ground Black Pepper', 'description' => 'Freshly Ground Black Pepper']);
        Ingredient::create(['name' => 'Freshly Ground Szechuan Peppercorns', 'description' => 'Freshly Ground Szechuan Peppercorns']);
        Ingredient::create(['name' => 'Freshly Minced Ginger', 'description' => 'Freshly Minced Ginger']);
        Ingredient::create(['name' => 'Frozen Corn', 'description' => 'Frozen Corn']);
        Ingredient::create(['name' => 'Frozen Peas', 'description' => 'Frozen Peas']);
        Ingredient::create(['name' => 'Frozen Peas Thawed', 'description' => 'Frozen Peas Thawed']);
        Ingredient::create(['name' => 'Frozen Spinach Thawed And Drained Of Excess Liquid', 'description' => 'Frozen Spinach Thawed And Drained Of Excess Liquid']);
        Ingredient::create(['name' => 'Garam Masala', 'description' => 'Garam Masala']);
        Ingredient::create(['name' => 'Garlic Clove, Minced', 'description' => 'Garlic Clove, Minced']);
        Ingredient::create(['name' => 'Garlic Cloves Minced', 'description' => 'Garlic Cloves Minced']);
        Ingredient::create(['name' => 'Garlic Cloves, Finely Chopped', 'description' => 'Garlic Cloves, Finely Chopped']);
        Ingredient::create(['name' => 'Garlic Cloves, Minced', 'description' => 'Garlic Cloves, Minced']);
        Ingredient::create(['name' => 'Garlic Cloves, Peeled And Smashed', 'description' => 'Garlic Cloves, Peeled And Smashed']);
        Ingredient::create(['name' => 'Garlic Powde', 'description' => 'Garlic Powde']);
        Ingredient::create(['name' => 'Garlic Powder', 'description' => 'Garlic Powder']);
        Ingredient::create(['name' => 'Garlic, Minced', 'description' => 'Garlic, Minced']);
        Ingredient::create(['name' => 'Grainy Mustard', 'description' => 'Grainy Mustard']);
        Ingredient::create(['name' => 'Granulated Sugar', 'description' => 'Granulated Sugar']);
        Ingredient::create(['name' => 'Grated Parmesan', 'description' => 'Grated Parmesan']);
        Ingredient::create(['name' => 'Greek Yogurt', 'description' => 'Greek Yogurt']);
        Ingredient::create(['name' => 'Green Bell Pepper, Chopped', 'description' => 'Green Bell Pepper, Chopped']);
        Ingredient::create(['name' => 'Green Bell Pepper, Sliced', 'description' => 'Green Bell Pepper, Sliced']);
        Ingredient::create(['name' => 'Green Chiles', 'description' => 'Green Chiles']);
        Ingredient::create(['name' => 'Green Onions Thinly Sliced', 'description' => 'Green Onions Thinly Sliced']);
        Ingredient::create(['name' => 'Green Onions, Cut Into 1 inch Pieces', 'description' => 'Green Onions, Cut Into 1 inch Pieces']);
        Ingredient::create(['name' => 'Green Onions, Thinly Sliced', 'description' => 'Green Onions, Thinly Sliced']);
        Ingredient::create(['name' => 'Ground Beef', 'description' => 'Ground Beef']);
        Ingredient::create(['name' => 'Ground Chicken', 'description' => 'Ground Chicken']);
        Ingredient::create(['name' => 'Ground Coriander', 'description' => 'Ground Coriander']);
        Ingredient::create(['name' => 'Ground Cumi', 'description' => 'Ground Cumi']);
        Ingredient::create(['name' => 'Ground Cumin', 'description' => 'Ground Cumin']);
        Ingredient::create(['name' => 'Ground Paprika', 'description' => 'Ground Paprika']);
        Ingredient::create(['name' => 'Guacamole', 'description' => 'Guacamole']);
        Ingredient::create(['name' => 'Half And Half Pinch Crushed Red Pepper Flakes', 'description' => 'Half And Half Pinch Crushed Red Pepper Flakes']);
        Ingredient::create(['name' => 'Halved Cherry Tomatoes', 'description' => 'Halved Cherry Tomatoes']);
        Ingredient::create(['name' => 'Harissa Paste', 'description' => 'Harissa Paste']);
        Ingredient::create(['name' => 'Head Of Garlic', 'description' => 'Head Of Garlic']);
        Ingredient::create(['name' => 'Heavy Cream', 'description' => 'Heavy Cream']);
        Ingredient::create(['name' => 'Hoisin Sauce', 'description' => 'Hoisin Sauce']);
        Ingredient::create(['name' => 'Honey', 'description' => 'Honey']);
        Ingredient::create(['name' => 'Hot Sauce', 'description' => 'Hot Sauce']);
        Ingredient::create(['name' => 'Hot Sauce (Such As Franks) Plus More For Drizzling (Optional)', 'description' => 'Hot Sauce (Such As Franks) Plus More For Drizzling (Optional)']);
        Ingredient::create(['name' => 'Italian Seasoning', 'description' => 'Italian Seasoning']);
        Ingredient::create(['name' => 'Jalapeño, Finely Chopped', 'description' => 'Jalapeño, Finely Chopped']);
        Ingredient::create(['name' => 'Jalapeño, Minced', 'description' => 'Jalapeño, Minced']);
        Ingredient::create(['name' => 'Jalapeño, Seeded And Minced, Plus More For Serving', 'description' => 'Jalapeño, Seeded And Minced, Plus More For Serving']);
        Ingredient::create(['name' => 'Jalapeños, Thinly Sliced, Divided', 'description' => 'Jalapeños, Thinly Sliced, Divided']);
        Ingredient::create(['name' => 'Juice And Zest Lemon', 'description' => 'Juice And Zest Lemon']);
        Ingredient::create(['name' => 'Juice Of 1 Lime', 'description' => 'Juice Of 1 Lime']);
        Ingredient::create(['name' => 'Juice Of 1/2 Lemon', 'description' => 'Juice Of 1/2 Lemon']);
        Ingredient::create(['name' => 'Juice Of 1/2 Lime', 'description' => 'Juice Of 1/2 Lime']);
        Ingredient::create(['name' => 'Juice Of 2 Limes', 'description' => 'Juice Of 2 Limes']);
        Ingredient::create(['name' => 'Juice Of Lemon', 'description' => 'Juice Of Lemon']);
        Ingredient::create(['name' => 'Juice Of Lemon (Optional)', 'description' => 'Juice Of Lemon (Optional)']);
        Ingredient::create(['name' => 'Juice Of Lime', 'description' => 'Juice Of Lime']);
        Ingredient::create(['name' => 'Ketchup', 'description' => 'Ketchup']);
        Ingredient::create(['name' => 'Kosher Salt', 'description' => 'Kosher Salt']);
        Ingredient::create(['name' => 'Kosher Salt, Divided', 'description' => 'Kosher Salt, Divided']);
        Ingredient::create(['name' => 'Kosher Salt, Plus More', 'description' => 'Kosher Salt, Plus More']);
        Ingredient::create(['name' => 'Large Boneless', 'description' => 'Large Boneless']);
        Ingredient::create(['name' => 'Large Carrot, Cut Into Irregular Chunks', 'description' => 'Large Carrot, Cut Into Irregular Chunks']);
        Ingredient::create(['name' => 'Large Cloves Garlic, Finely Chopped', 'description' => 'Large Cloves Garlic, Finely Chopped']);
        Ingredient::create(['name' => 'Large Egg', 'description' => 'Large Egg']);
        Ingredient::create(['name' => 'Large Egg, Beaten', 'description' => 'Large Egg, Beaten']);
        Ingredient::create(['name' => 'Large Eggs', 'description' => 'Large Eggs']);
        Ingredient::create(['name' => 'Large Eggs, Beaten', 'description' => 'Large Eggs, Beaten']);
        Ingredient::create(['name' => 'Large Eggs, Lightly Beaten', 'description' => 'Large Eggs, Lightly Beaten']);
        Ingredient::create(['name' => 'Large Flour Tortillas', 'description' => 'Large Flour Tortillas']);
        Ingredient::create(['name' => 'Large Head Cauliflower Cut Into Florets', 'description' => 'Large Head Cauliflower Cut Into Florets']);
        Ingredient::create(['name' => 'Large Leafy Lettuce (Leaves Separated For Serving', 'description' => 'Large Leafy Lettuce (Leaves Separated For Serving']);
        Ingredient::create(['name' => 'Large Onion Chopped', 'description' => 'Large Onion Chopped']);
        Ingredient::create(['name' => 'Large Onion, Chopped', 'description' => 'Large Onion, Chopped']);
        Ingredient::create(['name' => 'Large Shallot, Finely Chopped', 'description' => 'Large Shallot, Finely Chopped']);
        Ingredient::create(['name' => 'Large Shallots, Finely Chopped', 'description' => 'Large Shallots, Finely Chopped']);
        Ingredient::create(['name' => 'Large Shrimp, Peeled And Deveined', 'description' => 'Large Shrimp, Peeled And Deveined']);
        Ingredient::create(['name' => 'Large Sprigs Fresh Dill, Plus More For Serving', 'description' => 'Large Sprigs Fresh Dill, Plus More For Serving']);
        Ingredient::create(['name' => 'Large White Onions, One Peeled And Halved And The Other Thinly Sliced', 'description' => 'Large White Onions, One Peeled And Halved And The Other Thinly Sliced']);
        Ingredient::create(['name' => 'Large Yellow Onion, Diced', 'description' => 'Large Yellow Onion, Diced']);
        Ingredient::create(['name' => 'Large Zucchini, Cut Into Half Moons', 'description' => 'Large Zucchini, Cut Into Half Moons']);
        Ingredient::create(['name' => 'Lemon', 'description' => 'Lemon']);
        Ingredient::create(['name' => 'Lemon Juice', 'description' => 'Lemon Juice']);
        Ingredient::create(['name' => 'Lemon Juice (From 1 Lemon)', 'description' => 'Lemon Juice (From 1 Lemon)']);
        Ingredient::create(['name' => 'Lemon Juice, Plus 1 Lemon, Thinly Sliced', 'description' => 'Lemon Juice, Plus 1 Lemon, Thinly Sliced']);
        Ingredient::create(['name' => 'Lemon Pepper Seasoning', 'description' => 'Lemon Pepper Seasoning']);
        Ingredient::create(['name' => 'Lemon Wedges For Serving', 'description' => 'Lemon Wedges For Serving']);
        Ingredient::create(['name' => 'Lemon Wedges For Serving (Optional)', 'description' => 'Lemon Wedges For Serving (Optional)']);
        Ingredient::create(['name' => 'Lemon Wedges, For Serving', 'description' => 'Lemon Wedges, For Serving']);
        Ingredient::create(['name' => 'Lemon Zest', 'description' => 'Lemon Zest']);
        Ingredient::create(['name' => 'Lemon Zest, Divide', 'description' => 'Lemon Zest, Divide']);
        Ingredient::create(['name' => 'Lemon Zested And Thinly Sliced', 'description' => 'Lemon Zested And Thinly Sliced']);
        Ingredient::create(['name' => 'Lemon, Sliced Into Rounds', 'description' => 'Lemon, Sliced Into Rounds']);
        Ingredient::create(['name' => 'Lemons, Divided', 'description' => 'Lemons, Divided']);
        Ingredient::create(['name' => 'Light Brown Sugar', 'description' => 'Light Brown Sugar']);
        Ingredient::create(['name' => 'Lime Juice', 'description' => 'Lime Juice']);
        Ingredient::create(['name' => 'Lime Wedges', 'description' => 'Lime Wedges']);
        Ingredient::create(['name' => 'Lime Wedges For Serving', 'description' => 'Lime Wedges For Serving']);
        Ingredient::create(['name' => 'Lime Wedges, For Serving', 'description' => 'Lime Wedges, For Serving']);
        Ingredient::create(['name' => 'Long Grain Rice', 'description' => 'Long Grain Rice']);
        Ingredient::create(['name' => 'Long-grain Rice', 'description' => 'Long-grain Rice']);
        Ingredient::create(['name' => 'Low Moisture Whole Milk Mozzarella, Cut Into Small Cubes', 'description' => 'Low Moisture Whole Milk Mozzarella, Cut Into Small Cubes']);
        Ingredient::create(['name' => 'Low-sodium Beef (Or Chicken) Broth', 'description' => 'Low-sodium Beef (Or Chicken) Broth']);
        Ingredient::create(['name' => 'Low-sodium Beef Stock', 'description' => 'Low-sodium Beef Stock']);
        Ingredient::create(['name' => 'Low-sodium Chicken Broth', 'description' => 'Low-sodium Chicken Broth']);
        Ingredient::create(['name' => 'Low-sodium Chicken Stock', 'description' => 'Low-sodium Chicken Stock']);
        Ingredient::create(['name' => 'Low-sodium Soy Sauce', 'description' => 'Low-sodium Soy Sauce']);
        Ingredient::create(['name' => 'Low-sodium Soy Sauce, Divided', 'description' => 'Low-sodium Soy Sauce, Divided']);
        Ingredient::create(['name' => 'Low-sodium Vegetable Broth', 'description' => 'Low-sodium Vegetable Broth']);
        Ingredient::create(['name' => 'Low-sodium Vegetable Broth Or Water', 'description' => 'Low-sodium Vegetable Broth Or Water']);
        Ingredient::create(['name' => 'Marinara', 'description' => 'Marinara']);
        Ingredient::create(['name' => 'Marinara (Store-bought Or Homemade)', 'description' => 'Marinara (Store-bought Or Homemade)']);
        Ingredient::create(['name' => 'Marsala Wine', 'description' => 'Marsala Wine']);
        Ingredient::create(['name' => 'Medium Carrot, Peeled And Diced', 'description' => 'Medium Carrot, Peeled And Diced']);
        Ingredient::create(['name' => 'Medium Carrots, Cut Into In.', 'description' => 'Medium Carrots, Cut Into In.']);
        Ingredient::create(['name' => 'Medium Carrots, Diced', 'description' => 'Medium Carrots, Diced']);
        Ingredient::create(['name' => 'Medium Carrots, Peeled And Chopped', 'description' => 'Medium Carrots, Peeled And Chopped']);
        Ingredient::create(['name' => 'Medium Fuji Apple, Peeled And Grated', 'description' => 'Medium Fuji Apple, Peeled And Grated']);
        Ingredient::create(['name' => 'Medium Onion, Chopped', 'description' => 'Medium Onion, Chopped']);
        Ingredient::create(['name' => 'Medium Onion, Diced', 'description' => 'Medium Onion, Diced']);
        Ingredient::create(['name' => 'Medium Red Bell Pepper, Stemmed, Seeded, And Thinly Sliced', 'description' => 'Medium Red Bell Pepper, Stemmed, Seeded, And Thinly Sliced']);
        Ingredient::create(['name' => 'Medium Red Onion Thinly Sliced', 'description' => 'Medium Red Onion Thinly Sliced']);
        Ingredient::create(['name' => 'Medium Shrimp, Peeled And Deveined', 'description' => 'Medium Shrimp, Peeled And Deveined']);
        Ingredient::create(['name' => 'Medium Sweet Potatoes', 'description' => 'Medium Sweet Potatoes']);
        Ingredient::create(['name' => 'Medium White Onion, Sliced', 'description' => 'Medium White Onion, Sliced']);
        Ingredient::create(['name' => 'Medium Yellow Onion, Chopped', 'description' => 'Medium Yellow Onion, Chopped']);
        Ingredient::create(['name' => 'Medium Yellow Onion, Finely Chopped', 'description' => 'Medium Yellow Onion, Finely Chopped']);
        Ingredient::create(['name' => 'Milk', 'description' => 'Milk']);
        Ingredient::create(['name' => 'Minced Garlic Cloves', 'description' => 'Minced Garlic Cloves']);
        Ingredient::create(['name' => 'Mixed Mushrooms, Such As Maitake, Shiitake, Cremini, Or Oyster, Torn Or Sliced Into Bite-sized Pieces', 'description' => 'Mixed Mushrooms, Such As Maitake, Shiitake, Cremini, Or Oyster, Torn Or Sliced Into Bite-sized Pieces']);
        Ingredient::create(['name' => 'Monterey Jack Cheese, Shredded, Divided', 'description' => 'Monterey Jack Cheese, Shredded, Divided']);
        Ingredient::create(['name' => 'Nacho Cheese Sauce', 'description' => 'Nacho Cheese Sauce']);
        Ingredient::create(['name' => 'Non-dairy Milk', 'description' => 'Non-dairy Milk']);
        Ingredient::create(['name' => 'Nutritional Yeast', 'description' => 'Nutritional Yeast']);
        Ingredient::create(['name' => 'Oil-packed Anchovies Minced (Optional)', 'description' => 'Oil-packed Anchovies Minced (Optional)']);
        Ingredient::create(['name' => 'Old Bay Seasoning', 'description' => 'Old Bay Seasoning']);
        Ingredient::create(['name' => 'Olive Oil', 'description' => 'Olive Oil']);
        Ingredient::create(['name' => 'Olive Oil Cooking Spray Hot Sauce And Guacamole, For Serving', 'description' => 'Olive Oil Cooking Spray Hot Sauce And Guacamole, For Serving']);
        Ingredient::create(['name' => 'Olive Oil, Divided', 'description' => 'Olive Oil, Divided']);
        Ingredient::create(['name' => 'Onion Chopped', 'description' => 'Onion Chopped']);
        Ingredient::create(['name' => 'Onion Powder', 'description' => 'Onion Powder']);
        Ingredient::create(['name' => 'Onion, Chopped', 'description' => 'Onion, Chopped']);
        Ingredient::create(['name' => 'Oregano', 'description' => 'Oregano']);
        Ingredient::create(['name' => 'Oyster Sauce', 'description' => 'Oyster Sauce']);
        Ingredient::create(['name' => 'Package Gnocchi', 'description' => 'Package Gnocchi']);
        Ingredient::create(['name' => 'Package Refrigerated Potato Gnocchi', 'description' => 'Package Refrigerated Potato Gnocchi']);
        Ingredient::create(['name' => 'Packages Instant Ramen (Spice Packet Discarded)', 'description' => 'Packages Instant Ramen (Spice Packet Discarded)']);
        Ingredient::create(['name' => 'Packages Of Gnocchi', 'description' => 'Packages Of Gnocchi']);
        Ingredient::create(['name' => 'Packed Baby Spinach', 'description' => 'Packed Baby Spinach']);
        Ingredient::create(['name' => 'Packed Brown Sugar, Divided', 'description' => 'Packed Brown Sugar, Divided']);
        Ingredient::create(['name' => 'Pancetta, Cut Into 1/2 inch Pieces', 'description' => 'Pancetta, Cut Into 1/2 inch Pieces']);
        Ingredient::create(['name' => 'Panko', 'description' => 'Panko']);
        Ingredient::create(['name' => 'Panko Bread Crumbs', 'description' => 'Panko Bread Crumbs']);
        Ingredient::create(['name' => 'Paprika', 'description' => 'Paprika']);
        Ingredient::create(['name' => 'Parmesan, Finely Grated', 'description' => 'Parmesan, Finely Grated']);
        Ingredient::create(['name' => 'Pasta, Such As Rigatoni', 'description' => 'Pasta, Such As Rigatoni']);
        Ingredient::create(['name' => 'Peanut Or Vegetable Oil', 'description' => 'Peanut Or Vegetable Oil']);
        Ingredient::create(['name' => 'Penne', 'description' => 'Penne']);
        Ingredient::create(['name' => 'Pickled Jalapeños', 'description' => 'Pickled Jalapeños']);
        Ingredient::create(['name' => 'Pickled Red Onions', 'description' => 'Pickled Red Onions']);
        Ingredient::create(['name' => 'Piece Of Garlic, Quartered', 'description' => 'Piece Of Garlic, Quartered']);
        Ingredient::create(['name' => 'Pinch Crushed Red Pepper Flakes', 'description' => 'Pinch Crushed Red Pepper Flakes']);
        Ingredient::create(['name' => 'Pinch Crushed Red Pepper Flakes (Optional)', 'description' => 'Pinch Crushed Red Pepper Flakes (Optional)']);
        Ingredient::create(['name' => 'Pinch Of Ground Nutmeg', 'description' => 'Pinch Of Ground Nutmeg']);
        Ingredient::create(['name' => 'Pizza Dough Divided In Half', 'description' => 'Pizza Dough Divided In Half']);
        Ingredient::create(['name' => 'Poblano Peppers, Chopped', 'description' => 'Poblano Peppers, Chopped']);
        Ingredient::create(['name' => 'Potatoes, Peeled', 'description' => 'Potatoes, Peeled']);
        Ingredient::create(['name' => 'Quartered Cherry Tomatoes', 'description' => 'Quartered Cherry Tomatoes']);
        Ingredient::create(['name' => 'Radishes Thinly Sliced For Serving', 'description' => 'Radishes Thinly Sliced For Serving']);
        Ingredient::create(['name' => 'Raw Shrimp Peeled And Deveined', 'description' => 'Raw Shrimp Peeled And Deveined']);
        Ingredient::create(['name' => 'Red And Yellow Bell Peppers, Thinly Sliced', 'description' => 'Red And Yellow Bell Peppers, Thinly Sliced']);
        Ingredient::create(['name' => 'Red Bell Pepper, Chopped', 'description' => 'Red Bell Pepper, Chopped']);
        Ingredient::create(['name' => 'Red Bell Pepper, Sliced', 'description' => 'Red Bell Pepper, Sliced']);
        Ingredient::create(['name' => 'Red Bell Pepper, Stemmed, Seeded, And Chopped', 'description' => 'Red Bell Pepper, Stemmed, Seeded, And Chopped']);
        Ingredient::create(['name' => 'Red Curry Paste', 'description' => 'Red Curry Paste']);
        Ingredient::create(['name' => 'Red Onion Roughly Chopped', 'description' => 'Red Onion Roughly Chopped']);
        Ingredient::create(['name' => 'Red Onion, Chopped', 'description' => 'Red Onion, Chopped']);
        Ingredient::create(['name' => 'Red Pepper Flakes', 'description' => 'Red Pepper Flakes']);
        Ingredient::create(['name' => 'Ribs Celery, Chopped', 'description' => 'Ribs Celery, Chopped']);
        Ingredient::create(['name' => 'Rice Linguini Noodles', 'description' => 'Rice Linguini Noodles']);
        Ingredient::create(['name' => 'Rice Vinegar', 'description' => 'Rice Vinegar']);
        Ingredient::create(['name' => 'Rice Wine Vinegar', 'description' => 'Rice Wine Vinegar']);
        Ingredient::create(['name' => 'Rigatoni', 'description' => 'Rigatoni']);
        Ingredient::create(['name' => 'Roasted Peanuts, Chopped', 'description' => 'Roasted Peanuts, Chopped']);
        Ingredient::create(['name' => 'Roasted Unsalted Peanuts, For Garnish', 'description' => 'Roasted Unsalted Peanuts, For Garnish']);
        Ingredient::create(['name' => 'Rosemary Sprigs, For Skillet', 'description' => 'Rosemary Sprigs, For Skillet']);
        Ingredient::create(['name' => 'Roughly Chopped Toasted Walnuts', 'description' => 'Roughly Chopped Toasted Walnuts']);
        Ingredient::create(['name' => 'Russet Potato, Peeled And Cut Into Sixths', 'description' => 'Russet Potato, Peeled And Cut Into Sixths']);
        Ingredient::create(['name' => 'Salmon Fillets', 'description' => 'Salmon Fillets']);
        Ingredient::create(['name' => 'Salmon Fillets, Patted Dry With A Paper Towel', 'description' => 'Salmon Fillets, Patted Dry With A Paper Towel']);
        Ingredient::create(['name' => 'Salsa', 'description' => 'Salsa']);
        Ingredient::create(['name' => 'Salsa, For Serving', 'description' => 'Salsa, For Serving']);
        Ingredient::create(['name' => 'Sauce', 'description' => 'Sauce']);
        Ingredient::create(['name' => 'Scallions, White And Light Green Parts Cut Into 1 Pieces', 'description' => 'Scallions, White And Light Green Parts Cut Into 1 Pieces']);
        Ingredient::create(['name' => 'Sesame Oil', 'description' => 'Sesame Oil']);
        Ingredient::create(['name' => 'Sesame Oil (Divided)', 'description' => 'Sesame Oil (Divided)']);
        Ingredient::create(['name' => 'Sesame Seeds', 'description' => 'Sesame Seeds']);
        Ingredient::create(['name' => 'Sesame Seeds For Garnish', 'description' => 'Sesame Seeds For Garnish']);
        Ingredient::create(['name' => 'Shallot, Quartered', 'description' => 'Shallot, Quartered']);
        Ingredient::create(['name' => 'Shallot, Roughly Chopped', 'description' => 'Shallot, Roughly Chopped']);
        Ingredient::create(['name' => 'Shallot, Thinly Sliced', 'description' => 'Shallot, Thinly Sliced']);
        Ingredient::create(['name' => 'Shell-on Or Shelled Shrimp', 'description' => 'Shell-on Or Shelled Shrimp']);
        Ingredient::create(['name' => 'Sherdded Cooked Chicken', 'description' => 'Sherdded Cooked Chicken']);
        Ingredient::create(['name' => 'Shredded Cheddar', 'description' => 'Shredded Cheddar']);
        Ingredient::create(['name' => 'Shredded Cheddar, For Serving,', 'description' => 'Shredded Cheddar, For Serving,']);
        Ingredient::create(['name' => 'Shredded Cooked Chicken', 'description' => 'Shredded Cooked Chicken']);
        Ingredient::create(['name' => 'Shredded Lettuce', 'description' => 'Shredded Lettuce']);
        Ingredient::create(['name' => 'Shredded Mexican Cheese Blend, Divided', 'description' => 'Shredded Mexican Cheese Blend, Divided']);
        Ingredient::create(['name' => 'Shredded Monterey Jack', 'description' => 'Shredded Monterey Jack']);
        Ingredient::create(['name' => 'Shredded Mozzarella', 'description' => 'Shredded Mozzarella']);
        Ingredient::create(['name' => 'Shredded Pepper Jack', 'description' => 'Shredded Pepper Jack']);
        Ingredient::create(['name' => 'Shredded Pepper Jack Cheese', 'description' => 'Shredded Pepper Jack Cheese']);
        Ingredient::create(['name' => 'Shredded Provolone', 'description' => 'Shredded Provolone']);
        Ingredient::create(['name' => 'Shredded Purple Cabbage', 'description' => 'Shredded Purple Cabbage']);
        Ingredient::create(['name' => 'Shredded Rotisserie Chicken', 'description' => 'Shredded Rotisserie Chicken']);
        Ingredient::create(['name' => 'Shredded Smoked Gouda', 'description' => 'Shredded Smoked Gouda']);
        Ingredient::create(['name' => 'Shredded White Cheddar', 'description' => 'Shredded White Cheddar']);
        Ingredient::create(['name' => 'Shredded White Cheddar, For Serving', 'description' => 'Shredded White Cheddar, For Serving']);
        Ingredient::create(['name' => 'Shrimp Peeled And Deveined', 'description' => 'Shrimp Peeled And Deveined']);
        Ingredient::create(['name' => 'Shrimp, Peeled And Deveined', 'description' => 'Shrimp, Peeled And Deveined']);
        Ingredient::create(['name' => 'Shrimp, Peeled, Deveined, And Tails Removed', 'description' => 'Shrimp, Peeled, Deveined, And Tails Removed']);
        Ingredient::create(['name' => 'Sirloin Steak', 'description' => 'Sirloin Steak']);
        Ingredient::create(['name' => 'Sirloin Steak, Sliced Thinly Against Grain', 'description' => 'Sirloin Steak, Sliced Thinly Against Grain']);
        Ingredient::create(['name' => 'Skin-on Chicken Thighs', 'description' => 'Skin-on Chicken Thighs']);
        Ingredient::create(['name' => 'Skinless Chicken Breasts', 'description' => 'Skinless Chicken Breasts']);
        Ingredient::create(['name' => 'Sliced Avocado', 'description' => 'Sliced Avocado']);
        Ingredient::create(['name' => 'Sliced Cremini Mushrooms', 'description' => 'Sliced Cremini Mushrooms']);
        Ingredient::create(['name' => 'Sliced Green Cabbage, For Garnish', 'description' => 'Sliced Green Cabbage, For Garnish']);
        Ingredient::create(['name' => 'Sliced Scallion, For Garnish', 'description' => 'Sliced Scallion, For Garnish']);
        Ingredient::create(['name' => 'Small Boneless', 'description' => 'Small Boneless']);
        Ingredient::create(['name' => 'Small Carrot, Peeled, Trimmed, And Thinly Sliced Into Rounds', 'description' => 'Small Carrot, Peeled, Trimmed, And Thinly Sliced Into Rounds']);
        Ingredient::create(['name' => 'Small Jalapeño, Thinly Sliced', 'description' => 'Small Jalapeño, Thinly Sliced']);
        Ingredient::create(['name' => 'Small Plum Or Roma Tomatoes', 'description' => 'Small Plum Or Roma Tomatoes']);
        Ingredient::create(['name' => 'Small Potatoes, Halved', 'description' => 'Small Potatoes, Halved']);
        Ingredient::create(['name' => 'Small Red Onion, Halved', 'description' => 'Small Red Onion, Halved']);
        Ingredient::create(['name' => 'Small Red Onion, Thinly Sliced Into Quarter Moons', 'description' => 'Small Red Onion, Thinly Sliced Into Quarter Moons']);
        Ingredient::create(['name' => 'Small Roma Tomatoes, Chopped Into Large Pieces', 'description' => 'Small Roma Tomatoes, Chopped Into Large Pieces']);
        Ingredient::create(['name' => 'Small Shallot Diced', 'description' => 'Small Shallot Diced']);
        Ingredient::create(['name' => 'Small Yellow Onion', 'description' => 'Small Yellow Onion']);
        Ingredient::create(['name' => 'Small Yellow Onion Chopped', 'description' => 'Small Yellow Onion Chopped']);
        Ingredient::create(['name' => 'Small Yellow Onion, Chopped', 'description' => 'Small Yellow Onion, Chopped']);
        Ingredient::create(['name' => 'Small Yellow Onion, Diced', 'description' => 'Small Yellow Onion, Diced']);
        Ingredient::create(['name' => 'Small Yellow Onion, Finely Chopped', 'description' => 'Small Yellow Onion, Finely Chopped']);
        Ingredient::create(['name' => 'Small Yellow Onion, Thinly Sliced', 'description' => 'Small Yellow Onion, Thinly Sliced']);
        Ingredient::create(['name' => 'Smoked Paprika', 'description' => 'Smoked Paprika']);
        Ingredient::create(['name' => 'Smoked Salmon, Cut Into Bite Size Pieces', 'description' => 'Smoked Salmon, Cut Into Bite Size Pieces']);
        Ingredient::create(['name' => 'Snow Peas, Sliced On The Diagonal', 'description' => 'Snow Peas, Sliced On The Diagonal']);
        Ingredient::create(['name' => 'Sour Cream', 'description' => 'Sour Cream']);
        Ingredient::create(['name' => 'Sour Cream Plus More For Serving', 'description' => 'Sour Cream Plus More For Serving']);
        Ingredient::create(['name' => 'Sour Cream, For Serving', 'description' => 'Sour Cream, For Serving']);
        Ingredient::create(['name' => 'Soy Sauce, As Needed', 'description' => 'Soy Sauce, As Needed']);
        Ingredient::create(['name' => 'Spaghetti', 'description' => 'Spaghetti']);
        Ingredient::create(['name' => 'Sprigs Fresh Thyme', 'description' => 'Sprigs Fresh Thyme']);
        Ingredient::create(['name' => 'Sriracha', 'description' => 'Sriracha']);
        Ingredient::create(['name' => 'Sriracha (Optional)', 'description' => 'Sriracha (Optional)']);
        Ingredient::create(['name' => 'Sriracha Sauce(Optional)', 'description' => 'Sriracha Sauce(Optional)']);
        Ingredient::create(['name' => 'Stalks Celery, Chopped', 'description' => 'Stalks Celery, Chopped']);
        Ingredient::create(['name' => 'Stalks Celery, Diced', 'description' => 'Stalks Celery, Diced']);
        Ingredient::create(['name' => 'Stalks Celery, Sliced', 'description' => 'Stalks Celery, Sliced']);
        Ingredient::create(['name' => 'Store-bought Or Homemade Marinara Sauce', 'description' => 'Store-bought Or Homemade Marinara Sauce']);
        Ingredient::create(['name' => 'Swanson Chicken Broth', 'description' => 'Swanson Chicken Broth']);
        Ingredient::create(['name' => 'Sweet Potato, Peeled And Cubed', 'description' => 'Sweet Potato, Peeled And Cubed']);
        Ingredient::create(['name' => 'Tahini', 'description' => 'Tahini']);
        Ingredient::create(['name' => 'Thai Red Chilis, Thinly Sliced', 'description' => 'Thai Red Chilis, Thinly Sliced']);
        Ingredient::create(['name' => 'Thinly Sliced Basil', 'description' => 'Thinly Sliced Basil']);
        Ingredient::create(['name' => 'Thinly Sliced Basil For Garnish', 'description' => 'Thinly Sliced Basil For Garnish']);
        Ingredient::create(['name' => 'Thinly Sliced Cucumbers', 'description' => 'Thinly Sliced Cucumbers']);
        Ingredient::create(['name' => 'Thinly Sliced Green Onions For Garnish', 'description' => 'Thinly Sliced Green Onions For Garnish']);
        Ingredient::create(['name' => 'Thinly Sliced Radishes, For Garnish', 'description' => 'Thinly Sliced Radishes, For Garnish']);
        Ingredient::create(['name' => 'Tilapia Filets', 'description' => 'Tilapia Filets']);
        Ingredient::create(['name' => 'Tilapia Fillets', 'description' => 'Tilapia Fillets']);
        Ingredient::create(['name' => 'Tomato Past', 'description' => 'Tomato Past']);
        Ingredient::create(['name' => 'Tomato Paste', 'description' => 'Tomato Paste']);
        Ingredient::create(['name' => 'Tomatoes Thinly Sliced', 'description' => 'Tomatoes Thinly Sliced']);
        Ingredient::create(['name' => 'Torn Fresh Basil', 'description' => 'Torn Fresh Basil']);
        Ingredient::create(['name' => 'Tostada Shells', 'description' => 'Tostada Shells']);
        Ingredient::create(['name' => 'Tostadas', 'description' => 'Tostadas']);
        Ingredient::create(['name' => 'Uncooked Rice', 'description' => 'Uncooked Rice']);
        Ingredient::create(['name' => 'Unsalted Butter', 'description' => 'Unsalted Butter']);
        Ingredient::create(['name' => 'Vegetable Oil', 'description' => 'Vegetable Oil']);
        Ingredient::create(['name' => 'Vegetable Oil Divided', 'description' => 'Vegetable Oil Divided']);
        Ingredient::create(['name' => 'Vegetable Oil, For Frying', 'description' => 'Vegetable Oil, For Frying']);
        Ingredient::create(['name' => 'Vegetable Oil, For Pan', 'description' => 'Vegetable Oil, For Pan']);
        Ingredient::create(['name' => 'Vodka', 'description' => 'Vodka']);
        Ingredient::create(['name' => 'Warm Water', 'description' => 'Warm Water']);
        Ingredient::create(['name' => 'Water', 'description' => 'Water']);
        Ingredient::create(['name' => 'Wedges', 'description' => 'Wedges']);
        Ingredient::create(['name' => 'White Beans, Drained And Rinsed', 'description' => 'White Beans, Drained And Rinsed']);
        Ingredient::create(['name' => 'White Onion Minced For Serving', 'description' => 'White Onion Minced For Serving']);
        Ingredient::create(['name' => 'White Onion, Chopped', 'description' => 'White Onion, Chopped']);
        Ingredient::create(['name' => 'White Onion, Chopped, Divided', 'description' => 'White Onion, Chopped, Divided']);
        Ingredient::create(['name' => 'White Rice', 'description' => 'White Rice']);
        Ingredient::create(['name' => 'White Sesame Seeds, For Garnish', 'description' => 'White Sesame Seeds, For Garnish']);
        Ingredient::create(['name' => 'White Wine', 'description' => 'White Wine']);
        Ingredient::create(['name' => 'Whole Milk', 'description' => 'Whole Milk']);
        Ingredient::create(['name' => 'Wide Egg Noodles', 'description' => 'Wide Egg Noodles']);
        Ingredient::create(['name' => 'Wide Rice Noodles', 'description' => 'Wide Rice Noodles']);
        Ingredient::create(['name' => 'Yellow Bell Pepper, Chopped', 'description' => 'Yellow Bell Pepper, Chopped']);
        Ingredient::create(['name' => 'Yellow Onion, Finely Chopped', 'description' => 'Yellow Onion, Finely Chopped']);
        Ingredient::create(['name' => 'Yellow Onion, Thinly Sliced', 'description' => 'Yellow Onion, Thinly Sliced']);
        Ingredient::create(['name' => 'Yellow Squash Cut Into Half-moons', 'description' => 'Yellow Squash Cut Into Half-moons']);
        Ingredient::create(['name' => 'Zest And Juice Of Lemon', 'description' => 'Zest And Juice Of Lemon']);
        Ingredient::create(['name' => 'Zest Of 1 Lemon (Optional)', 'description' => 'Zest Of 1 Lemon (Optional)']);
        Ingredient::create(['name' => 'Zucchini Cut Into Half-moons', 'description' => 'Zucchini Cut Into Half-moons']);
        Ingredient::create(['name' => 'Basil, Chopped', 'description' => 'Basil, Chopped']);
        Ingredient::create(['name' => 'Ground Turkey', 'description' => 'Ground Turkey']);
        Ingredient::create(['name' => 'Spicy Or Sweet Italian Sausage', 'description' => 'Spicy Or Sweet Italian Sausage']);
        Ingredient::create(['name' => 'Pasta', 'description' => 'Pasta']);
        Ingredient::create(['name' => 'Tomatoes', 'description' => 'Tomatoes']);
        Ingredient::create(['name' => 'Sweet Chili Sauce', 'description' => 'Sweet Chili Sauce']);
        Ingredient::create(['name' => 'Rice Flour', 'description' => 'Rice Flour']);
        Ingredient::create(['name' => 'Sprigs Fresh Rosemary', 'description' => 'Sprigs Fresh Rosemary']);
        Ingredient::create(['name' => 'Can Chickpeas', 'description' => 'Can Chickpeas']);
        Ingredient::create(['name' => 'Mayonnaise', 'description' => 'Mayonnaise']);
        Ingredient::create(['name' => 'Pitas', 'description' => 'Pitas']);
    }
}
